### ISSUE TITLE
Deploy mainnet nodes CD error: resource is not ready

### ISSUE THREAD

**Issue by teor2345** [ZcashFoundation/zebra#1785]
## Motivation

There was a single mainnet deployment failure with the error:
> The resource 'projects/zealous-zebra/regions/us-east1/instanceGroupManagers/zebrad-main' is not ready

This error happened when two PRs were merged less than a minute apart.

It seems like a rare situation, so I'm marking this `P-Medium`.

## Solution

We should skip the mainnet deploy job if it is already running:
https://github.com/marketplace/actions/skip-duplicate-actions

I think we'll want a config that cancels the newer jobs, because we can't cancel a deployment that's halfway done:
```yaml
concurrent_skipping: 'always'
cancel_others: false
```

## Logs

```
Run gcloud compute instance-groups managed rolling-action start-update \
ERROR: (gcloud.compute.instance-groups.managed.rolling-action.start-update) Could not fetch resource:
 - The resource 'projects/zealous-zebra/regions/us-east1/instanceGroupManagers/zebrad-main' is not ready
```

**Comment by teor2345** [comment]
This seems to have been solved.

**Comment by gustavovalverde** [comment]
Reopening as this is still happening when multiple PRs get merged at the same time: https://github.com/ZcashFoundation/zebra/runs/8065354827?check_suite_focus=true#step:7:65
